+++
# About/Biography widget.
widget = "about"
active = true
#date = 2016-04-20T00:00:00

# Order that this section will appear in.
weight = 5

# List your academic interests.
[interests]
  interests = [
    "Political Psychology",
    "Prejudice, Race, and Politics",
    "Belief Systems"
  ]

# List your qualifications (such as academic degrees).
[[education.courses]]
  course = "PhD in Political Science"
  institution = "Vanderbilt University"
  year = Expected 2019

[[education.courses]]
  course = "BA in Government"
  institution = "The College of William & Mary"
  year = 2013


# Biography
I am a political science Ph.D. candidate at Vanderbilt University. My research focuses on political behavior and public opinion in the United States, centering on the intersection of group politics and social and economic inequality. Substantively I am interested in areas ranging from political party coalitions to race and ethnic politics. My dissertation project explores how political elites shape the ways whites understand race, flipping the conventional wisdom that racial attitudes are consistently pre-political. I employ correlational, text analytic, and experimental methods to answer these questions. I am also interested in methodological issues related to capturing individuals’ beliefs and attitudes, and effectively linking theoretical constructs with empirical measures.